### PR TITLE
Initial Commit first design drafts

### PR DESCRIPTION
**Pull request by DiamessoGroup**
First draft of design for contact management app.

### CODE REVIEW

**Comment by wguldin** [comment]
Thanks for your submission @DiamessoGroup! If you are interested in the position still, please file an application at:

**Comment by DiamessoGroup** [comment]
Hello Will,

I have received the notification that you have closed the pull request.

I was still working on it. I had made the pull request because I read in the project description that you wanted to see the way the app evolves I think. But I might have misunderstood.

I should complete the project this weekend. Would you like me to just do a final pull request?

I just have to add the documentation, the user testing, and some interactivity.

Also, I had already submitted my application for the Ui/Ux position.

**Comment by wguldin** [comment]
Good to hear you submitted an application.

We do want to see your progress, I just closed the pull request because I thought it was complete. 

Go ahead and reopen it when your PR is complete. Thanks!

**Comment by DiamessoGroup** [comment]
Thanks @wguldin . I will notify you as well.
Have a good day.

**Pull request closed without merging**
